version: "3"
services:
  web:
    build: .
    ports:
    - "9000:9000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
    - "20717:20717"